### PR TITLE
Issue #219

### PR DESCRIPTION
**Pull request by genoud**
Catch errors during diff handling and display them in the output

### CODE REVIEW

**Comment by manisfdcsfdx** [comment]
@azlam-abdulsalam @genoud this is good to merge.

**Comment by manisfdcsfdx** [comment]
Hey @genoud just noticed some behavior. after catching even if there is a error it is not stopping, it is printing the detailed error in table. should we throw the error and fail the command ?

**Comment by genoud** [comment]
Hey @manisfdcsfdx this was the previous behaviour of the command. We though it would be better to process the whole project and display errors.

**Comment by genoud** [comment]
@azlam-abdulsalam do you agree with this?

**Comment by manisfdcsfdx** [comment]
@azlamsalam @genoud . Tested, All good. if error found exception thrown in the end.

**Pull request merged**
