### PR TITLE
Fix Diff Command issue #104

### PR DESCRIPTION
**Pull request by genoud**
Copy .forceignore and sfdx-project.json. check existence before Copy
Copy of folder stating with . (.circleci for example)
permissionSet management:
    Incremental deployment in API 39 and earlier
    Full deployment in API 40 and later

### CODE REVIEW

**Comment by genoud** [comment]
> @genoud Why do we need to copy Copy of folder stating with . (.circleci for example)? Because the way I see it, these are part of the actual project, and we are just generating a diff.. so does it matter?

Hello,
We had a bug when a file located in a folder starting with dot was changed. This just fix that bug.

**Comment by azlam-abdulsalam** [comment]
> > @genoud Why do we need to copy Copy of folder stating with . (.circleci for example)? Because the way I see it, these are part of the actual project, and we are just generating a diff.. so does it matter?
> 
> Hello,
> We had a bug when a file located in a folder starting with dot was changed. This just fix that bug.

What was the file?

**Comment by genoud** [comment]
config.yml for circleci for example if a project is using circleci.

**Comment by azlam-abdulsalam** [comment]
> config.yml for circleci for example if a project is using circleci.

i think we should not be bothered by such files..we should just only worry about metatada diff

**Comment by genoud** [comment]
> > config.yml for circleci for example if a project is using circleci.
> 
> i think we should not be bothered by such files..we should just only worry about metatada diff
Ok. So far the diff command was just moving all files listed in the git diff command output.

**Comment by azlam-abdulsalam** [comment]
> > > config.yml for circleci for example if a project is using circleci.
> > 
> > 
> > i think we should not be bothered by such files..we should just only worry about metatada diff
> > Ok. So far the diff command was just moving all files listed in the git diff command output.

Cool.. how can we get this resolved? may be diff only on the directories mentioned in the sfdx-project.json?

**Comment by genoud** [comment]
> > > > config.yml for circleci for example if a project is using circleci.
> > > 
> > > 
> > > i think we should not be bothered by such files..we should just only worry about metatada diff
> > > Ok. So far the diff command was just moving all files listed in the git diff command output.
> 
> Cool.. how can we get this resolved? may be diff only on the directories mentioned in the sfdx-project.json?

Yes, this is a good idea.

**Comment by azlam-abdulsalam** [comment]
@genoud  Can you reraise thr PR with the conflicts resolved?

**Comment by genoud** [comment]
> @genoud Can you reraise thr PR with the conflicts resolved?

Done

**Pull request merged**
