### PR TITLE
fix:issue #571

### PR DESCRIPTION
**Pull request by genoud**
Fix retrieve issue hapening when -f parameter is used and some profiles
in folder does not exists in the org.

### CODE REVIEW

**Comment by MarcDBehr** [comment]
@genoud I tried following the directions to test (cloned the repository, checked out the issue/571 branch and ran sfdx plugins:link. When I try to run the retrieve command, I get:

```
$ sfdx sfpowerkit:source:profile:retrieve  -h
 ›   Warning: sfpowerkit:source:profile:retrieve is not a sfdx command.
Did you mean force:source:retrieve? [y/n]: 
```

Reinstalling the plugin, the command works.  Am I testing it wrong?

**Comment by vuha-acn** [comment]
> @genoud I tried following the directions to test (cloned the repository, checked out the issue/571 branch and ran sfdx plugins:link. When I try to run the retrieve command, I get:
> 
> ```
> $ sfdx sfpowerkit:source:profile:retrieve  -h
>  ›   Warning: sfpowerkit:source:profile:retrieve is not a sfdx command.
> Did you mean force:source:retrieve? [y/n]: 
> ```
> 
> Reinstalling the plugin, the command works. Am I testing it wrong?

@MarcDBehr - Can you confirm that you navigated to the downloaded local copy of the repository and "cd sfpowerkit" into that directory before running the sfdx plugins:link command? Also, did you do the full sfdx plugins:uninstall sfpowerkit command first? It looks like it didn't fully get reinstalled/linked back so it's not recognizing the command.

**Comment by MarcDBehr** [comment]
@vuha-acn 


Here is what I did (and just redid):

```
marc@marc-E6540:~/Projects/sfpowerkit$ sfdx plugins
@dx-cli-toolbox/sfdx-toolbox-package-utils 0.7.1
@oclif/plugin-autocomplete 0.3.0
bbdoc 3.6.1
dependencies-cli 2.0.1
limits 1.2.1
sfdmu 4.4.5
sfdx-waw-plugin 1.5.0

marc@marc-E6540:~/Projects/sfpowerkit$ sfdx plugins:link
(node:224609) Warning: Mismatched version in sfpowerkit plugin manifest. Expected: 3.3.0 Received: 3.2.3
This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be automatically generated when publishing.
(Use `node --trace-warnings ...` to show where the warning was created)
sfdx-cli: linking plugin sfpowerkit... done
sfpowerkit 3.3.0 (link) /home/marc/Projects/sfpowerkit

marc@marc-E6540:~/Projects/sfpowerkit$ sfdx sfpowerkit:source:profile:retrieve  -h
(node:224722) Warning: Mismatched version in sfpowerkit plugin manifest. Expected: 3.3.0 Received: 3.2.3
This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be automatically generated when publishing.
(Use `node --trace-warnings ...` to show where the warning was created)
 ›   Warning: sfpowerkit:source:profile:retrieve is not a sfdx command.
Did you mean force:source:retrieve? [y/n]: 
 ›   Error: Run sfdx help sfpowerkit for a list of available commands.

marc@marc-E6540:~/Projects/sfpowerkit$ sfdx plugins
(node:224922) Warning: Mismatched version in sfpowerkit plugin manifest. Expected: 3.3.0 Received: 3.2.3
This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be automatically generated when publishing.
(Use `node --trace-warnings ...` to show where the warning was created)
@dx-cli-toolbox/sfdx-toolbox-package-utils 0.7.1
@oclif/plugin-autocomplete 0.3.0
bbdoc 3.6.1
dependencies-cli 2.0.1
limits 1.2.1
sfdmu 4.4.5
sfdx-waw-plugin 1.5.0
sfpowerkit 3.3.0 (link) /home/marc/Projects/sfpowerkit

```

**Comment by genoud** [comment]
@MarcDBehr I updated the oclif.manifest.json file. Checkout the change and link it again

**Comment by MarcDBehr** [comment]
@genoud Got a different error now:

```
marc@marc-E6540:~/Projects/sfpowerkit$ git checkout issues/571
Switched to branch 'issues/571'
Your branch is up to date with 'origin/issues/571'.
marc@marc-E6540:~/Projects/sfpowerkit$ git fetch && git pull
Already up to date.
marc@marc-E6540:~/Projects/sfpowerkit$ sfdx plugins:link
sfdx-cli: linking plugin sfpowerkit... done
marc@marc-E6540:~/Projects/sfpowerkit$ sfdx sfpowerkit:source:profile:retrieve  -h
    Error: Cannot find module '/home/marc/Projects/sfpowerkit/lib/commands/sfpowerkit/source/profile/retrieve'
    Require stack:
    - /usr/local/share/.config/yarn/global/node_modules/@oclif/config/lib/plugin.js
    - /usr/local/share/.config/yarn/global/node_modules/@oclif/config/lib/config.js
    - /usr/local/share/.config/yarn/global/node_modules/@oclif/config/lib/index.js
    - /usr/local/share/.config/yarn/global/node_modules/@oclif/command/lib/command.js
    - /usr/local/share/.config/yarn/global/node_modules/@oclif/command/lib/index.js
    - /usr/local/share/.config/yarn/global/node_modules/sfdx-cli/dist/cli.js
    - /usr/local/share/.config/yarn/global/node_modules/sfdx-cli/bin/run
    Code: MODULE_NOT_FOUND
```

**Comment by azlam-abdulsalam** [comment]
@MarcDBehr  you need to do a npm i, on the root directory for it to download dependencies. But be assured, we are testing it out

**Comment by MarcDBehr** [comment]
Looks like it works, but I don't get any message indicating that there was an issue with the profile.

I installed the existing plugin and created a local profile that does not exist on the org. 
```
$ sfdx sfpowerkit:source:profile:retrieve -u qa -f force-app/main/default/profiles/ 
INFO [2021-09-30 10:16:53.060 +0000] (sfpowerkit): Number of profiles found in the target org 39
Loading profiles in batches  - PROGRESS  | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 0/39  ProfilesERROR running sfpowerkit:source:profile:retrieve:  The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
```
Same error as before. Then I uninstalled the release version and did a plugins:link and ran the same command 
```
marc@marc-E6540:~/Projects/comres$ sfdx plugins:uninstall sfpowerkit
warning ../../../package.json: No license field
warning "@oclif/plugin-autocomplete > @oclif/command@1.5.19" has unmet peer dependency "@oclif/plugin-help@^2".
Uninstalling sfpowerkit... done
marc@marc-E6540:~/Projects/comres$ cd ../sfpowerkit/
marc@marc-E6540:~/Projects/sfpowerkit$ sfdx plugins:link
sfdx-cli: linking plugin sfpowerkit... done
marc@marc-E6540:~/Projects/sfpowerkit$ cd -
/home/marc/Projects/comres
marc@marc-E6540:~/Projects/comres$ sfdx sfpowerkit:source:profile:retrieve -u qa -f force-app/main/default/profiles/ 
INFO [2021-09-30 10:18:42.069 +0000] (sfpowerkit): Number of profiles found in the target org 38
Loading profiles in batches  - PROGRESS  | ████████████████████████████████████████ | 38/38  Profiles
State    Full Name                           Type     Path
───────  ──────────────────────────────────  ───────  ───────────────────────────────────────────────────────────────────────────────────
Updated  Admin                               Profile  force-app/main/default/profiles/Admin.profile-meta.xml
[...]
```
I found one less profile on the org, so it only tried to download 38 rather than 39 profiles, but it provided no indication that it was skipping one

**Comment by azlam-abdulsalam** [comment]
@genoud  Can you review the changes?

**Review by genoud — COMMENTED** [review]
Tested, works fine

**Pull request merged**
