### PR TITLE
FIX Issue #97: Empty output folder before diff

### PR DESCRIPTION
**Pull request by genoud**

### CODE REVIEW

**Comment by azlam-abdulsalam** [comment]
@genoud  I believe this is for issue #95  and not for issue #97, Could you amend the commit message?

**Comment by genoud** [comment]
No it for issue #97.

**Comment by azlam-abdulsalam** [comment]
Got it, in that case we need also to show an error message of both to and from is the same revision as well

**Comment by genoud** [comment]
Yes we can still do it.
But as on git we have several way to point on a revision, this will just
result in comparing the strings provided by the user. HEAD^4 may be the
same commit as tag v1.1 for example. In this case we will not throw an
error and the result will still be empty.

**Comment by azlam-abdulsalam** [comment]
Yes, can we resolve it to the actual commit id and then do a compare.?

I will merge the current change for an immediate fix , lets do some thinking about it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
